/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class CommonFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CommonFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(CommonFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(CommonFactory obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof CommonFactory)
      equal = (((CommonFactory)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public DisplayFactory GetDisplayFactory() {
    long cPtr = jniJNI.CommonFactory_GetDisplayFactory(swigCPtr, this);
    return (cPtr == 0) ? null : new DisplayFactory(cPtr, false);
  }

  public SpatialReferenceFactory CreateCRSFactory() {
    long cPtr = jniJNI.CommonFactory_CreateCRSFactory(swigCPtr, this);
    return (cPtr == 0) ? null : new SpatialReferenceFactory(cPtr, false);
  }

  public GeometryFactory CreateGeometryFactory(SpatialReference h) {
    long cPtr = jniJNI.CommonFactory_CreateGeometryFactory(swigCPtr, this, SpatialReference.getCPtr(h), h);
    return (cPtr == 0) ? null : new GeometryFactory(cPtr, false);
  }

  public LayerSourceFactory GetLayerSourceFactory() {
    long cPtr = jniJNI.CommonFactory_GetLayerSourceFactory(swigCPtr, this);
    return (cPtr == 0) ? null : new LayerSourceFactory(cPtr, false);
  }

  public FeatureTypeStyleFactory CreateFeatureTypeStyleFactory() {
    long cPtr = jniJNI.CommonFactory_CreateFeatureTypeStyleFactory(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureTypeStyleFactory(cPtr, false);
  }

  public CoverageFactory CreateCoverageFactory() {
    long cPtr = jniJNI.CommonFactory_CreateCoverageFactory(swigCPtr, this);
    return (cPtr == 0) ? null : new CoverageFactory(cPtr, false);
  }

  public Parameters CreateParameters() {
    long cPtr = jniJNI.CommonFactory_CreateParameters(swigCPtr, this);
    return (cPtr == 0) ? null : new Parameters(cPtr, false);
  }

  public Parameter CreateParameter() {
    long cPtr = jniJNI.CommonFactory_CreateParameter(swigCPtr, this);
    return (cPtr == 0) ? null : new Parameter(cPtr, false);
  }

  public Utility CreateUtility() {
    long cPtr = jniJNI.CommonFactory_CreateUtility(swigCPtr, this);
    return (cPtr == 0) ? null : new Utility(cPtr, false);
  }

  public Message CreateMessage() {
    long cPtr = jniJNI.CommonFactory_CreateMessage(swigCPtr, this);
    return (cPtr == 0) ? null : new Message(cPtr, false);
  }

  public LocationSensor GetLocationSensor() {
    long cPtr = jniJNI.CommonFactory_GetLocationSensor(swigCPtr, this);
    return (cPtr == 0) ? null : new LocationSensor(cPtr, false);
  }

  public MotionSensor GetMotionSensor() {
    long cPtr = jniJNI.CommonFactory_GetMotionSensor(swigCPtr, this);
    return (cPtr == 0) ? null : new MotionSensor(cPtr, false);
  }

  public VideoSensor GetVideoSensor() {
    long cPtr = jniJNI.CommonFactory_GetVideoSensor(swigCPtr, this);
    return (cPtr == 0) ? null : new VideoSensor(cPtr, false);
  }

  public ColorRampList GetColorRampList() {
    long cPtr = jniJNI.CommonFactory_GetColorRampList(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorRampList(cPtr, false);
  }

  public LayerSource GetSystemLayerSource() {
    long cPtr = jniJNI.CommonFactory_GetSystemLayerSource(swigCPtr, this);
    return (cPtr == 0) ? null : new LayerSource(cPtr, false);
  }

  public FeatureType CreateFeatureType(String pszName) {
    long cPtr = jniJNI.CommonFactory_CreateFeatureType(swigCPtr, this, pszName);
    return (cPtr == 0) ? null : new FeatureType(cPtr, false);
  }

  public FeatureAttributeDescriptor CreateFeatureAttributeDescriptor(String pszName, int fieldtype) {
    long cPtr = jniJNI.CommonFactory_CreateFeatureAttributeDescriptor(swigCPtr, this, pszName, fieldtype);
    return (cPtr == 0) ? null : new FeatureAttributeDescriptor(cPtr, false);
  }

  public FeatureQuery CreateFeatureQuery() {
    long cPtr = jniJNI.CommonFactory_CreateFeatureQuery(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureQuery(cPtr, false);
  }

  public AttributeIndex CreateAttributeIndex() {
    long cPtr = jniJNI.CommonFactory_CreateAttributeIndex(swigCPtr, this);
    return (cPtr == 0) ? null : new AttributeIndex(cPtr, false);
  }

  public LocationService CreateLocationService() {
    long cPtr = jniJNI.CommonFactory_CreateLocationService(swigCPtr, this);
    return (cPtr == 0) ? null : new LocationService(cPtr, false);
  }

}
