/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GraphicLineString extends Graphic {
  private long swigCPtr;

  protected GraphicLineString(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.GraphicLineString_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GraphicLineString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GraphicLineString obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GraphicLineString)
      equal = (((GraphicLineString)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void AddPoint(float x, float y) {
    jniJNI.GraphicLineString_AddPoint(swigCPtr, this, x, y);
  }

  public void DeletePoint(int index) {
    jniJNI.GraphicLineString_DeletePoint(swigCPtr, this, index);
  }

  public void InsertPoint(int index, float x, float y) {
    jniJNI.GraphicLineString_InsertPoint(swigCPtr, this, index, x, y);
  }

  public void SetPoint(int index, float x, float y) {
    jniJNI.GraphicLineString_SetPoint(swigCPtr, this, index, x, y);
  }

  public boolean IsClosed() {
    return jniJNI.GraphicLineString_IsClosed(swigCPtr, this);
  }

}
