/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GraphicScaledImage extends Graphic {
  private long swigCPtr;

  protected GraphicScaledImage(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.GraphicScaledImage_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GraphicScaledImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GraphicScaledImage obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GraphicScaledImage)
      equal = (((GraphicScaledImage)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetScaledImageFromString(String pszFileName) {
    jniJNI.GraphicScaledImage_SetScaledImageFromString(swigCPtr, this, pszFileName);
  }

  public void SetUpperLeft(float x, float y) {
    jniJNI.GraphicScaledImage_SetUpperLeft(swigCPtr, this, x, y);
  }

  public void GetUpperLeft(SWIGTYPE_p_float x, SWIGTYPE_p_float y) {
    jniJNI.GraphicScaledImage_GetUpperLeft(swigCPtr, this, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y));
  }

  public void SetLowerRight(float x, float y) {
    jniJNI.GraphicScaledImage_SetLowerRight(swigCPtr, this, x, y);
  }

  public void GetLowerRight(SWIGTYPE_p_float x, SWIGTYPE_p_float y) {
    jniJNI.GraphicScaledImage_GetLowerRight(swigCPtr, this, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y));
  }

  public void SetIntensity(int intensity) {
    jniJNI.GraphicScaledImage_SetIntensity(swigCPtr, this, intensity);
  }

  public int GetIntensity() {
    return jniJNI.GraphicScaledImage_GetIntensity(swigCPtr, this);
  }

  public void SetTransparency(int transparency) {
    jniJNI.GraphicScaledImage_SetTransparency(swigCPtr, this, transparency);
  }

  public int GetTransparency() {
    return jniJNI.GraphicScaledImage_GetTransparency(swigCPtr, this);
  }

  public void SetCRS(SpatialReference crs) {
    jniJNI.GraphicScaledImage_SetCRS(swigCPtr, this, SpatialReference.getCPtr(crs), crs);
  }

  public SpatialReference GetCRS() {
    long cPtr = jniJNI.GraphicScaledImage_GetCRS(swigCPtr, this);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

}
