/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GraphicIcon extends Graphic {
  private long swigCPtr;

  protected GraphicIcon(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.GraphicIcon_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GraphicIcon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GraphicIcon obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GraphicIcon)
      equal = (((GraphicIcon)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetIconFromString(String pszFilePath) {
    jniJNI.GraphicIcon_SetIconFromString(swigCPtr, this, pszFilePath);
  }

  public void SetPosition(float x, float y) {
    jniJNI.GraphicIcon_SetPosition(swigCPtr, this, x, y);
  }

  public void GetPosition(SWIGTYPE_p_float x, SWIGTYPE_p_float y) {
    jniJNI.GraphicIcon_GetPosition(swigCPtr, this, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y));
  }

  public void SetOffset(float x, float y) {
    jniJNI.GraphicIcon_SetOffset(swigCPtr, this, x, y);
  }

  public void GetOffset(SWIGTYPE_p_float x, SWIGTYPE_p_float y) {
    jniJNI.GraphicIcon_GetOffset(swigCPtr, this, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y));
  }

}
