/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class LayerSourceFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LayerSourceFactory(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(LayerSourceFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniJNI.delete_LayerSourceFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(LayerSourceFactory obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof LayerSourceFactory)
      equal = (((LayerSourceFactory)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public LayerSource CreateLayerSource(String c) {
    long cPtr = jniJNI.LayerSourceFactory_CreateLayerSource(swigCPtr, this, c);
    return (cPtr == 0) ? null : new LayerSource(cPtr, false);
  }

  public LayerSource CreateNewLayerSource(String c) {
    long cPtr = jniJNI.LayerSourceFactory_CreateNewLayerSource(swigCPtr, this, c);
    return (cPtr == 0) ? null : new LayerSource(cPtr, false);
  }

  public boolean CanProcess(String c) {
    return jniJNI.LayerSourceFactory_CanProcess(swigCPtr, this, c);
  }

  public String GetIcon() {
    return jniJNI.LayerSourceFactory_GetIcon(swigCPtr, this);
  }

  public void SetIcon(String c) {
    jniJNI.LayerSourceFactory_SetIcon(swigCPtr, this, c);
  }

  public String GetDisplayName() {
    return jniJNI.LayerSourceFactory_GetDisplayName(swigCPtr, this);
  }

  public void SetDisplayName(String c) {
    jniJNI.LayerSourceFactory_SetDisplayName(swigCPtr, this, c);
  }

  public String GetDescription() {
    return jniJNI.LayerSourceFactory_GetDescription(swigCPtr, this);
  }

  public void SetDescription(String c) {
    jniJNI.LayerSourceFactory_SetDescription(swigCPtr, this, c);
  }

  public boolean IsAvailable() {
    return jniJNI.LayerSourceFactory_IsAvailable(swigCPtr, this);
  }

}
