/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class LocationSensor extends Sensor {
  private long swigCPtr;

  protected LocationSensor(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.LocationSensor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocationSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(LocationSensor obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof LocationSensor)
      equal = (((LocationSensor)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public short GetPortNumber() {
    return jniJNI.LocationSensor_GetPortNumber(swigCPtr, this);
  }

  public int GetBaudRate() {
    return jniJNI.LocationSensor_GetBaudRate(swigCPtr, this);
  }

  public int GetLocationSensorType() {
    return jniJNI.LocationSensor_GetLocationSensorType(swigCPtr, this);
  }

  public void SetLocationSensorType(int eType) {
    jniJNI.LocationSensor_SetLocationSensorType(swigCPtr, this, eType);
  }

  public void SetUnknownSensor(int StartPos, int UnitSize, int AdStartPos, int AdUnitSize, int HexStartPos, int HexUnitSize) {
    jniJNI.LocationSensor_SetUnknownSensor(swigCPtr, this, StartPos, UnitSize, AdStartPos, AdUnitSize, HexStartPos, HexUnitSize);
  }

}
