/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class LocationService {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LocationService(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(LocationService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(LocationService obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof LocationService)
      equal = (((LocationService)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.LocationService_Destroy(swigCPtr, this);
  }

  public String GeoCode(String pszAddr, String pszOption) {
    return jniJNI.LocationService_GeoCode(swigCPtr, this, pszAddr, pszOption);
  }

  public String RevGeoCode(double x, double y, String pszOption, SpatialReference poSrcSRS) {
    return jniJNI.LocationService_RevGeoCode(swigCPtr, this, x, y, pszOption, SpatialReference.getCPtr(poSrcSRS), poSrcSRS);
  }

  public String NearestName(String pszKeyword, String pszOption) {
    return jniJNI.LocationService_NearestName(swigCPtr, this, pszKeyword, pszOption);
  }

  public String NearestPoint(double x, double y, String pszKeyword, String pszOption, SpatialReference poSrcSRS) {
    return jniJNI.LocationService_NearestPoint(swigCPtr, this, x, y, pszKeyword, pszOption, SpatialReference.getCPtr(poSrcSRS), poSrcSRS);
  }

  public String WithinDistance(double x, double y, String pszKeyword, double dlMinDist, double dlMaxDist, String pszOption, SpatialReference poSrcSRS) {
    return jniJNI.LocationService_WithinDistance(swigCPtr, this, x, y, pszKeyword, dlMinDist, dlMaxDist, pszOption, SpatialReference.getCPtr(poSrcSRS), poSrcSRS);
  }

  public FeatureCollection RouteDetermine(Geometry poStartPt, Geometry poEndPt, SpatialReference poSrcSRS) {
    long cPtr = jniJNI.LocationService_RouteDetermine(swigCPtr, this, Geometry.getCPtr(poStartPt), poStartPt, Geometry.getCPtr(poEndPt), poEndPt, SpatialReference.getCPtr(poSrcSRS), poSrcSRS);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureLayer WithinFeature(LayerSource poLySrc, Layer poLayer, double x, double y, Parameters poParams) {
    long cPtr = jniJNI.LocationService_WithinFeature(swigCPtr, this, LayerSource.getCPtr(poLySrc), poLySrc, Layer.getCPtr(poLayer), poLayer, x, y, Parameters.getCPtr(poParams), poParams);
    return (cPtr == 0) ? null : new FeatureLayer(cPtr, false);
  }

}
