/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class PrintLayoutWidget extends Widget {
  private long swigCPtr;

  protected PrintLayoutWidget(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.PrintLayoutWidget_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrintLayoutWidget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(PrintLayoutWidget obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof PrintLayoutWidget)
      equal = (((PrintLayoutWidget)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public boolean ReadXML(String filename) {
    return jniJNI.PrintLayoutWidget_ReadXML(swigCPtr, this, filename);
  }

  public boolean WriteXML(String filename) {
    return jniJNI.PrintLayoutWidget_WriteXML(swigCPtr, this, filename);
  }

  public void Destroy() {
    jniJNI.PrintLayoutWidget_Destroy(swigCPtr, this);
  }

  public boolean GetDisplayToolBarByType(int eType) {
    return jniJNI.PrintLayoutWidget_GetDisplayToolBarByType(swigCPtr, this, eType);
  }

  public void SetDisplayToolBarByType(int eType, boolean visible) {
    jniJNI.PrintLayoutWidget_SetDisplayToolBarByType(swigCPtr, this, eType, visible);
  }

  public void SetDisplayToolBar(boolean visible) {
    jniJNI.PrintLayoutWidget_SetDisplayToolBar(swigCPtr, this, visible);
  }

  public void DeleteToolBarByType(int eType) {
    jniJNI.PrintLayoutWidget_DeleteToolBarByType(swigCPtr, this, eType);
  }

  public boolean GetDisplayMenuBar() {
    return jniJNI.PrintLayoutWidget_GetDisplayMenuBar(swigCPtr, this);
  }

  public void SetDisplayMenuBar(boolean visible) {
    jniJNI.PrintLayoutWidget_SetDisplayMenuBar(swigCPtr, this, visible);
  }

  public PrintLayoutItem GetItem(String itemid) {
    long cPtr = jniJNI.PrintLayoutWidget_GetItem(swigCPtr, this, itemid);
    return (cPtr == 0) ? null : new PrintLayoutItem(cPtr, false);
  }

  public void SetDisplayProperyWidget(boolean visible) {
    jniJNI.PrintLayoutWidget_SetDisplayProperyWidget(swigCPtr, this, visible);
  }

  public void SetKeyEnable(int key, int enable) {
    jniJNI.PrintLayoutWidget_SetKeyEnable(swigCPtr, this, key, enable);
  }

  public void SetMouseButtonEnable(int key, int enable) {
    jniJNI.PrintLayoutWidget_SetMouseButtonEnable(swigCPtr, this, key, enable);
  }

  public void Invalidate() {
    jniJNI.PrintLayoutWidget_Invalidate(swigCPtr, this);
  }

}
