/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class PrintLayoutItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PrintLayoutItem(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(PrintLayoutItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(PrintLayoutItem obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof PrintLayoutItem)
      equal = (((PrintLayoutItem)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetText(String text) {
    jniJNI.PrintLayoutItem_SetText(swigCPtr, this, text);
  }

  public void SetMapCenter(double centerx, double centery, double scale) {
    jniJNI.PrintLayoutItem_SetMapCenter(swigCPtr, this, centerx, centery, scale);
  }

  public void SetMapScale(double scale) {
    jniJNI.PrintLayoutItem_SetMapScale(swigCPtr, this, scale);
  }

  public void SetMapRelativeScale(double scaleDenominator) {
    jniJNI.PrintLayoutItem_SetMapRelativeScale(swigCPtr, this, scaleDenominator);
  }

  public void SetMapRect(double minx, double miny, double maxx, double maxy) {
    jniJNI.PrintLayoutItem_SetMapRect(swigCPtr, this, minx, miny, maxx, maxy);
  }

  public void SetMapRotation(double angle) {
    jniJNI.PrintLayoutItem_SetMapRotation(swigCPtr, this, angle);
  }

  public void SetImageFile(String filename) {
    jniJNI.PrintLayoutItem_SetImageFile(swigCPtr, this, filename);
  }

  public void SetPosition(double x, double y, int position, int page) {
    jniJNI.PrintLayoutItem_SetPosition(swigCPtr, this, x, y, position, page);
  }

  public void Move(double x, double y, double width, double height, int position, int page) {
    jniJNI.PrintLayoutItem_Move(swigCPtr, this, x, y, width, height, position, page);
  }

}
