/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class TabWidget extends Widget {
  private long swigCPtr;

  protected TabWidget(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.TabWidget_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TabWidget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(TabWidget obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof TabWidget)
      equal = (((TabWidget)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void AddTab(String pszTitle, Widget poWidget) {
    jniJNI.TabWidget_AddTab(swigCPtr, this, pszTitle, Widget.getCPtr(poWidget), poWidget);
  }

  public Canvas AddCanvas(String pszTitle, String pszCanvas) {
    long cPtr = jniJNI.TabWidget_AddCanvas(swigCPtr, this, pszTitle, pszCanvas);
    return (cPtr == 0) ? null : new Canvas(cPtr, false);
  }

  public Map2D AddMap2D(String pszTitle) {
    long cPtr = jniJNI.TabWidget_AddMap2D(swigCPtr, this, pszTitle);
    return (cPtr == 0) ? null : new Map2D(cPtr, false);
  }

  public Map3D AddMap3D(String pszTitle) {
    long cPtr = jniJNI.TabWidget_AddMap3D(swigCPtr, this, pszTitle);
    return (cPtr == 0) ? null : new Map3D(cPtr, false);
  }

  public MapEarth AddMapEarth(String pszTitle) {
    long cPtr = jniJNI.TabWidget_AddMapEarth(swigCPtr, this, pszTitle);
    return (cPtr == 0) ? null : new MapEarth(cPtr, false);
  }

  public MapAR AddMapAR(String pszTitle) {
    long cPtr = jniJNI.TabWidget_AddMapAR(swigCPtr, this, pszTitle);
    return (cPtr == 0) ? null : new MapAR(cPtr, false);
  }

}
