/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class AttributeIndex {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AttributeIndex(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(AttributeIndex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(AttributeIndex obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof AttributeIndex)
      equal = (((AttributeIndex)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.AttributeIndex_Destroy(swigCPtr, this);
  }

  public FeatureCollection GetFeatureCollection() {
    long cPtr = jniJNI.AttributeIndex_GetFeatureCollection(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public void SetFeatureCollection(FeatureCollection h) {
    jniJNI.AttributeIndex_SetFeatureCollection(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public void Create(int nField) {
    jniJNI.AttributeIndex_Create(swigCPtr, this, nField);
  }

  public void Remove(int nField) {
    jniJNI.AttributeIndex_Remove(swigCPtr, this, nField);
  }

  public FeatureCollection SubCollection(Geometry geom, int h) {
    long cPtr = jniJNI.AttributeIndex_SubCollection(swigCPtr, this, Geometry.getCPtr(geom), geom, h);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

}
