/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class DockWidget extends Widget {
  private long swigCPtr;

  protected DockWidget(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.DockWidget_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DockWidget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(DockWidget obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof DockWidget)
      equal = (((DockWidget)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetWidget(String pszTitle, Widget poWidget) {
    jniJNI.DockWidget_SetWidget(swigCPtr, this, pszTitle, Widget.getCPtr(poWidget), poWidget);
  }

  public void SetAllowedAreas(short nAreas) {
    jniJNI.DockWidget_SetAllowedAreas(swigCPtr, this, nAreas);
  }

  public Canvas SetCanvas(String pszTitle, String pszCanvas) {
    long cPtr = jniJNI.DockWidget_SetCanvas(swigCPtr, this, pszTitle, pszCanvas);
    return (cPtr == 0) ? null : new Canvas(cPtr, false);
  }

  public Map2D SetCanvasToMap2D(String pszTitle, String pszCanvas) {
    long cPtr = jniJNI.DockWidget_SetCanvasToMap2D(swigCPtr, this, pszTitle, pszCanvas);
    return (cPtr == 0) ? null : new Map2D(cPtr, false);
  }

  public int GetFeatures() {
    return jniJNI.DockWidget_GetFeatures(swigCPtr, this);
  }

  public void SetFeatures(int nFeature) {
    jniJNI.DockWidget_SetFeatures(swigCPtr, this, nFeature);
  }

}
