/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Event {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Event(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Event obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniJNI.delete_Event(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Event obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Event)
      equal = (((Event)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public Event() {
    this(jniJNI.new_Event(), true);
  }

  public void OnEventDestroy() {
    jniJNI.Event_OnEventDestroy(swigCPtr, this);
  }

  public int Reference() {
    return jniJNI.Event_Reference(swigCPtr, this);
  }

  public int Dereference() {
    return jniJNI.Event_Dereference(swigCPtr, this);
  }

  public void Release() {
    jniJNI.Event_Release(swigCPtr, this);
  }

  public int GetRefCount() {
    return jniJNI.Event_GetRefCount(swigCPtr, this);
  }

}
