/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class FeatureAttributeDescriptor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FeatureAttributeDescriptor(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(FeatureAttributeDescriptor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(FeatureAttributeDescriptor obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof FeatureAttributeDescriptor)
      equal = (((FeatureAttributeDescriptor)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public FeatureAttributeDescriptor(String name_null_ok, SWIGTYPE_p_OGRFieldType data_type) {
    this(jniJNI.new_FeatureAttributeDescriptor__SWIG_0(name_null_ok, SWIGTYPE_p_OGRFieldType.getCPtr(data_type)), true);
  }

  public FeatureAttributeDescriptor(String name_null_ok) {
    this(jniJNI.new_FeatureAttributeDescriptor__SWIG_1(name_null_ok), true);
  }

  public FeatureAttributeDescriptor() {
    this(jniJNI.new_FeatureAttributeDescriptor__SWIG_2(), true);
  }

  public void Destroy() {
    jniJNI.FeatureAttributeDescriptor_Destroy(swigCPtr, this);
  }

  public String GetName() {
    return jniJNI.FeatureAttributeDescriptor_GetName(swigCPtr, this);
  }

  public void SetName(String name) {
    jniJNI.FeatureAttributeDescriptor_SetName(swigCPtr, this, name);
  }

  public int GetType() {
    return jniJNI.FeatureAttributeDescriptor_GetType(swigCPtr, this);
  }

  public void SetType(int type) {
    jniJNI.FeatureAttributeDescriptor_SetType(swigCPtr, this, type);
  }

  public int GetSize() {
    return jniJNI.FeatureAttributeDescriptor_GetSize(swigCPtr, this);
  }

  public void SetSize(int size) {
    jniJNI.FeatureAttributeDescriptor_SetSize(swigCPtr, this, size);
  }

  public int GetPrecision() {
    return jniJNI.FeatureAttributeDescriptor_GetPrecision(swigCPtr, this);
  }

  public void SetPrecision(int precision) {
    jniJNI.FeatureAttributeDescriptor_SetPrecision(swigCPtr, this, precision);
  }

  public int GetMinimumOccurrences() {
    return jniJNI.FeatureAttributeDescriptor_GetMinimumOccurrences(swigCPtr, this);
  }

  public void SetMinimumOccurrences(int newVal) {
    jniJNI.FeatureAttributeDescriptor_SetMinimumOccurrences(swigCPtr, this, newVal);
  }

  public int GetMaximumOccurrences() {
    return jniJNI.FeatureAttributeDescriptor_GetMaximumOccurrences(swigCPtr, this);
  }

  public void SetMaximumOccurrences(int newVal) {
    jniJNI.FeatureAttributeDescriptor_SetMaximumOccurrences(swigCPtr, this, newVal);
  }

  public String GetTitle() {
    return jniJNI.FeatureAttributeDescriptor_GetTitle(swigCPtr, this);
  }

  public void SetTitle(String pszTitle) {
    jniJNI.FeatureAttributeDescriptor_SetTitle(swigCPtr, this, pszTitle);
  }

  public Layer GetReferLayer() {
    long cPtr = jniJNI.FeatureAttributeDescriptor_GetReferLayer(swigCPtr, this);
    return (cPtr == 0) ? null : new Layer(cPtr, false);
  }

  public void SetReferLayer(Layer layer) {
    jniJNI.FeatureAttributeDescriptor_SetReferLayer(swigCPtr, this, Layer.getCPtr(layer), layer);
  }

  public FeatureAttributeDescriptor GetReferField() {
    long cPtr = jniJNI.FeatureAttributeDescriptor_GetReferField(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureAttributeDescriptor(cPtr, false);
  }

  public void SetReferField(FeatureAttributeDescriptor refer) {
    jniJNI.FeatureAttributeDescriptor_SetReferField(swigCPtr, this, FeatureAttributeDescriptor.getCPtr(refer), refer);
  }

  public String GetReferLayerName() {
    return jniJNI.FeatureAttributeDescriptor_GetReferLayerName(swigCPtr, this);
  }

  public void SetReferLayerName(String name) {
    jniJNI.FeatureAttributeDescriptor_SetReferLayerName(swigCPtr, this, name);
  }

  public String GetReferFieldName() {
    return jniJNI.FeatureAttributeDescriptor_GetReferFieldName(swigCPtr, this);
  }

  public void SetReferFieldName(String name) {
    jniJNI.FeatureAttributeDescriptor_SetReferFieldName(swigCPtr, this, name);
  }

  public long GetVisibleAuth() {
    return jniJNI.FeatureAttributeDescriptor_GetVisibleAuth(swigCPtr, this);
  }

  public void SetVisibleAuth(long auth) {
    jniJNI.FeatureAttributeDescriptor_SetVisibleAuth(swigCPtr, this, auth);
  }

  public long GetEditableAuth() {
    return jniJNI.FeatureAttributeDescriptor_GetEditableAuth(swigCPtr, this);
  }

  public void SetEditableAuth(long auth) {
    jniJNI.FeatureAttributeDescriptor_SetEditableAuth(swigCPtr, this, auth);
  }

  public boolean IsNullable() {
    return jniJNI.FeatureAttributeDescriptor_IsNullable(swigCPtr, this);
  }

  public void SetNullable(boolean nullable) {
    jniJNI.FeatureAttributeDescriptor_SetNullable(swigCPtr, this, nullable);
  }

  public boolean IsSeqKey() {
    return jniJNI.FeatureAttributeDescriptor_IsSeqKey(swigCPtr, this);
  }

  public void SetSeqKey(boolean seqkey) {
    jniJNI.FeatureAttributeDescriptor_SetSeqKey(swigCPtr, this, seqkey);
  }

  public int GetValidValueSize() {
    return jniJNI.FeatureAttributeDescriptor_GetValidValueSize(swigCPtr, this);
  }

  public FeatureAttributeValidValue GetValidValue(int idx) {
    long cPtr = jniJNI.FeatureAttributeDescriptor_GetValidValue(swigCPtr, this, idx);
    return (cPtr == 0) ? null : new FeatureAttributeValidValue(cPtr, false);
  }

  public FeatureAttributeDescriptor Clone() {
    long cPtr = jniJNI.FeatureAttributeDescriptor_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureAttributeDescriptor(cPtr, false);
  }

}
