/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class FeatureTypeStyleFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FeatureTypeStyleFactory(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(FeatureTypeStyleFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(FeatureTypeStyleFactory obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof FeatureTypeStyleFactory)
      equal = (((FeatureTypeStyleFactory)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.FeatureTypeStyleFactory_Destroy(swigCPtr, this);
  }

  public FeatureTypeStyle CreateFeatureTypeStyle() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateFeatureTypeStyle(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureTypeStyle(cPtr, false);
  }

  public FeatureTypeStyle CreateFeatureTypeStyleFromXML(String xmlFile) {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateFeatureTypeStyleFromXML(swigCPtr, this, xmlFile);
    return (cPtr == 0) ? null : new FeatureTypeStyle(cPtr, false);
  }

  public Symbolizer CreateSymbolizer() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateSymbolizer(swigCPtr, this);
    return (cPtr == 0) ? null : new Symbolizer(cPtr, false);
  }

  public FeatureTypeStyleRule CreateFeatureTypeStyleRule() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateFeatureTypeStyleRule(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureTypeStyleRule(cPtr, false);
  }

  public Fill CreateFillStyle() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateFillStyle(swigCPtr, this);
    return (cPtr == 0) ? null : new Fill(cPtr, false);
  }

  public Stroke CreateStrokeStyle() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateStrokeStyle(swigCPtr, this);
    return (cPtr == 0) ? null : new Stroke(cPtr, false);
  }

  public Mark CreateMarkStyle() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateMarkStyle(swigCPtr, this);
    return (cPtr == 0) ? null : new Mark(cPtr, false);
  }

  public Font CreateFontStyle() {
    long cPtr = jniJNI.FeatureTypeStyleFactory_CreateFontStyle(swigCPtr, this);
    return (cPtr == 0) ? null : new Font(cPtr, false);
  }

}
