/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GridCoverageProcessor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GridCoverageProcessor(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(GridCoverageProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GridCoverageProcessor obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GridCoverageProcessor)
      equal = (((GridCoverageProcessor)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public int GetNumOperations() {
    return jniJNI.GridCoverageProcessor_GetNumOperations(swigCPtr, this);
  }

  public GridOperation GetOperation(int op) {
    long cPtr = jniJNI.GridCoverageProcessor_GetOperation(swigCPtr, this, op);
    return (cPtr == 0) ? null : new GridOperation(cPtr, false);
  }

  public GridOperation GetOperationByName(String name) {
    long cPtr = jniJNI.GridCoverageProcessor_GetOperationByName(swigCPtr, this, name);
    return (cPtr == 0) ? null : new GridOperation(cPtr, false);
  }

  public GridCoverage DoOperation(String pStr, Parameters poParam) {
    long cPtr = jniJNI.GridCoverageProcessor_DoOperation(swigCPtr, this, pStr, Parameters.getCPtr(poParam), poParam);
    return (cPtr == 0) ? null : new GridCoverage(cPtr, false);
  }

}
