/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class IndexMapWidget extends Widget {
  private long swigCPtr;

  protected IndexMapWidget(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.IndexMapWidget_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexMapWidget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(IndexMapWidget obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof IndexMapWidget)
      equal = (((IndexMapWidget)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public Map2D GetCanvas() {
    long cPtr = jniJNI.IndexMapWidget_GetCanvas(swigCPtr, this);
    return (cPtr == 0) ? null : new Map2D(cPtr, false);
  }

  public void AddFeatureLayer(FeatureLayer poFtLayer) {
    jniJNI.IndexMapWidget_AddFeatureLayer(swigCPtr, this, FeatureLayer.getCPtr(poFtLayer), poFtLayer);
  }

  public void SetScaleRatio(double ratio) {
    jniJNI.IndexMapWidget_SetScaleRatio(swigCPtr, this, ratio);
  }

  public double GetScaleRatio() {
    return jniJNI.IndexMapWidget_GetScaleRatio(swigCPtr, this);
  }

  public boolean GetIndexMapAutoMove() {
    return jniJNI.IndexMapWidget_GetIndexMapAutoMove(swigCPtr, this);
  }

  public void SetIndexMapAutoMove(boolean val) {
    jniJNI.IndexMapWidget_SetIndexMapAutoMove(swigCPtr, this, val);
  }

  public boolean GetCanMoveIndexMap() {
    return jniJNI.IndexMapWidget_GetCanMoveIndexMap(swigCPtr, this);
  }

  public void SetCanMoveIndexMap(boolean val) {
    jniJNI.IndexMapWidget_SetCanMoveIndexMap(swigCPtr, this, val);
  }

}
