/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class SpatialReferenceFactory {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SpatialReferenceFactory(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(SpatialReferenceFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(SpatialReferenceFactory obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof SpatialReferenceFactory)
      equal = (((SpatialReferenceFactory)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.SpatialReferenceFactory_Destroy(swigCPtr, this);
  }

  public SpatialReference CreateFromWKT(String pszVal) {
    long cPtr = jniJNI.SpatialReferenceFactory_CreateFromWKT(swigCPtr, this, pszVal);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

  public SpatialReference CreateFromProj4(String pszVal) {
    long cPtr = jniJNI.SpatialReferenceFactory_CreateFromProj4(swigCPtr, this, pszVal);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

  public SpatialReference CreateFromXML(String pszVal) {
    long cPtr = jniJNI.SpatialReferenceFactory_CreateFromXML(swigCPtr, this, pszVal);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

  public SpatialReference CreateFromESRI(String pszVal) {
    long cPtr = jniJNI.SpatialReferenceFactory_CreateFromESRI(swigCPtr, this, pszVal);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

  public GeographicTransform CreateGeographicTransform() {
    long cPtr = jniJNI.SpatialReferenceFactory_CreateGeographicTransform(swigCPtr, this);
    return (cPtr == 0) ? null : new GeographicTransform(cPtr, false);
  }

}
