/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Stroke {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Stroke(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Stroke obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Stroke obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Stroke)
      equal = (((Stroke)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public String GetColor() {
    return jniJNI.Stroke_GetColor(swigCPtr, this);
  }

  public void SetColor(String pszVal) {
    jniJNI.Stroke_SetColor(swigCPtr, this, pszVal);
  }

  public double GetWidth() {
    return jniJNI.Stroke_GetWidth(swigCPtr, this);
  }

  public void SetWidth(double dVal) {
    jniJNI.Stroke_SetWidth(swigCPtr, this, dVal);
  }

  public String GetPattern() {
    return jniJNI.Stroke_GetPattern(swigCPtr, this);
  }

  public void SetPattern(String pszVal) {
    jniJNI.Stroke_SetPattern(swigCPtr, this, pszVal);
  }

}
