/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class SWIGTYPE_p_OGRFieldType {
  private long swigCPtr;

  protected SWIGTYPE_p_OGRFieldType(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_OGRFieldType() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_OGRFieldType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

