/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Widget {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Widget(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Widget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Widget obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Widget)
      equal = (((Widget)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Initialize(int handle) {
    jniJNI.Widget_Initialize(swigCPtr, this, handle);
  }

  public void ReSize(int x, int y, int width, int height) {
    jniJNI.Widget_ReSize(swigCPtr, this, x, y, width, height);
  }

  public void Destroy() {
    jniJNI.Widget_Destroy(swigCPtr, this);
  }

  public void AddWidget(Widget poWidget) {
    jniJNI.Widget_AddWidget(swigCPtr, this, Widget.getCPtr(poWidget), poWidget);
  }

  public void AddWidgetByLayout(Widget poWidget, int row, int col) {
    jniJNI.Widget_AddWidgetByLayout(swigCPtr, this, Widget.getCPtr(poWidget), poWidget, row, col);
  }

  public void SetCanvas(Map2D poCanvas) {
    jniJNI.Widget_SetCanvas(swigCPtr, this, Map2D.getCPtr(poCanvas), poCanvas);
  }

  public void SetFeatureCanvas(FeatureCanvas poFtCanvas) {
    jniJNI.Widget_SetFeatureCanvas(swigCPtr, this, FeatureCanvas.getCPtr(poFtCanvas), poFtCanvas);
  }

  public void SetFeatureLayer(FeatureLayer poFtLayer) {
    jniJNI.Widget_SetFeatureLayer(swigCPtr, this, FeatureLayer.getCPtr(poFtLayer), poFtLayer);
  }

}
