/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class ColorModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ColorModel(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(ColorModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(ColorModel obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof ColorModel)
      equal = (((ColorModel)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public int GetInterpretation() {
    return jniJNI.ColorModel_GetInterpretation(swigCPtr, this);
  }

  public int GetNumColor() {
    return jniJNI.ColorModel_GetNumColor(swigCPtr, this);
  }

  public void SetColor(int index, short c1, short c2, short c3, short c4) {
    jniJNI.ColorModel_SetColor(swigCPtr, this, index, c1, c2, c3, c4);
  }

  public int GetColorAsRGB(int index) {
    return jniJNI.ColorModel_GetColorAsRGB(swigCPtr, this, index);
  }

}
