/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class FeatureCollection {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FeatureCollection(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(FeatureCollection obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(FeatureCollection obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof FeatureCollection)
      equal = (((FeatureCollection)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.FeatureCollection_Destroy(swigCPtr, this);
  }

  public boolean IsEmpty() {
    return jniJNI.FeatureCollection_IsEmpty(swigCPtr, this);
  }

  public int GetSize() {
    return jniJNI.FeatureCollection_GetSize(swigCPtr, this);
  }

  public int Size() {
    return jniJNI.FeatureCollection_Size(swigCPtr, this);
  }

  public int GetLabelSize(Layer layer) {
    return jniJNI.FeatureCollection_GetLabelSize(swigCPtr, this, Layer.getCPtr(layer), layer);
  }

  public int GetTransaction() {
    return jniJNI.FeatureCollection_GetTransaction(swigCPtr, this);
  }

  public void SetTransaction(int h) {
    jniJNI.FeatureCollection_SetTransaction(swigCPtr, this, h);
  }

  public Feature GetFeature() {
    long cPtr = jniJNI.FeatureCollection_GetFeature(swigCPtr, this);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public Feature GetFeatureFromFID(int nFID) {
    long cPtr = jniJNI.FeatureCollection_GetFeatureFromFID(swigCPtr, this, nFID);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public FeatureLayer GetFeatureLayer() {
    long cPtr = jniJNI.FeatureCollection_GetFeatureLayer(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureLayer(cPtr, false);
  }

  public int IsRefer() {
    return jniJNI.FeatureCollection_IsRefer(swigCPtr, this);
  }

  public void SetRefer(int nVal) {
    jniJNI.FeatureCollection_SetRefer(swigCPtr, this, nVal);
  }

  public boolean Contains(Feature h) {
    return jniJNI.FeatureCollection_Contains(swigCPtr, this, Feature.getCPtr(h), h);
  }

  public boolean ContainsAll(FeatureCollection h) {
    return jniJNI.FeatureCollection_ContainsAll(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public Feature Add(Feature h) {
    long cPtr = jniJNI.FeatureCollection_Add(swigCPtr, this, Feature.getCPtr(h), h);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public void AddAll(FeatureCollection h) {
    jniJNI.FeatureCollection_AddAll(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public void Clear() {
    jniJNI.FeatureCollection_Clear(swigCPtr, this);
  }

  public boolean Remove(Feature h) {
    return jniJNI.FeatureCollection_Remove(swigCPtr, this, Feature.getCPtr(h), h);
  }

  public boolean RemoveAll(FeatureCollection h) {
    return jniJNI.FeatureCollection_RemoveAll(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public boolean RetainAll(FeatureCollection h) {
    return jniJNI.FeatureCollection_RetainAll(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public FeatureCollection SubCollection(FeatureQuery h) {
    long cPtr = jniJNI.FeatureCollection_SubCollection(swigCPtr, this, FeatureQuery.getCPtr(h), h);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public void Close() {
    jniJNI.FeatureCollection_Close(swigCPtr, this);
  }

  public short MoveFirst() {
    return jniJNI.FeatureCollection_MoveFirst(swigCPtr, this);
  }

  public short MoveNext() {
    return jniJNI.FeatureCollection_MoveNext(swigCPtr, this);
  }

  public short MovePrevious() {
    return jniJNI.FeatureCollection_MovePrevious(swigCPtr, this);
  }

  public short MoveLast() {
    return jniJNI.FeatureCollection_MoveLast(swigCPtr, this);
  }

  public Feature SetFeature(Feature newh) {
    long cPtr = jniJNI.FeatureCollection_SetFeature(swigCPtr, this, Feature.getCPtr(newh), newh);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public Feature CreateFeature() {
    long cPtr = jniJNI.FeatureCollection_CreateFeature(swigCPtr, this);
    return (cPtr == 0) ? null : new Feature(cPtr, false);
  }

  public String ExportLTM(String pszLayerID, Geometry poTileEnv, String pszFilePath, short nLevel, int nX, int nY, int bAdd, short nFlag, int bDegreeUnit, short nAnnoFieldIndex, int bClip, float fVersion) {
    return jniJNI.FeatureCollection_ExportLTM(swigCPtr, this, pszLayerID, Geometry.getCPtr(poTileEnv), poTileEnv, pszFilePath, nLevel, nX, nY, bAdd, nFlag, bDegreeUnit, nAnnoFieldIndex, bClip, fVersion);
  }

  public void GetBounds(double[] argout) {
    jniJNI.FeatureCollection_GetBounds(swigCPtr, this, argout);
  }

  public void ReCalculateExtent() {
    jniJNI.FeatureCollection_ReCalculateExtent(swigCPtr, this);
  }

  public FeatureCollection ClipGeometry(FeatureCollection poFtCol, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_ClipGeometry(swigCPtr, this, FeatureCollection.getCPtr(poFtCol), poFtCol, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection IntersectGeometry(FeatureCollection poFtCol, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_IntersectGeometry(swigCPtr, this, FeatureCollection.getCPtr(poFtCol), poFtCol, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection BoundaryGeometry(boolean bResultUnion, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_BoundaryGeometry(swigCPtr, this, bResultUnion, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection BufferGeometry(double distance, int quadsegs, boolean bResultUnion, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_BufferGeometry(swigCPtr, this, distance, quadsegs, bResultUnion, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection BufferGeometryWithStyle(double width, int quadsegs, int endCapStyle, int joinStyle, double mitreLimit, boolean bResultUnion, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_BufferGeometryWithStyle(swigCPtr, this, width, quadsegs, endCapStyle, joinStyle, mitreLimit, bResultUnion, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection BufferGeometryWithSingleSide(double width, int quadsegs, int joinStyle, double mitreLimit, boolean bLeftSide, boolean bResultUnion, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_BufferGeometryWithSingleSide(swigCPtr, this, width, quadsegs, joinStyle, mitreLimit, bLeftSide, bResultUnion, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection UnionGeometry(FeatureCollection poFtCol, boolean bResultUnion, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_UnionGeometry(swigCPtr, this, FeatureCollection.getCPtr(poFtCol), poFtCol, bResultUnion, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection DifferenceGeometry(FeatureCollection poFtCol, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_DifferenceGeometry(swigCPtr, this, FeatureCollection.getCPtr(poFtCol), poFtCol, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection SymmetricDifferenceGeometry(FeatureCollection poFtCol, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_SymmetricDifferenceGeometry(swigCPtr, this, FeatureCollection.getCPtr(poFtCol), poFtCol, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Merge(FeatureCollection poFtCol, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Merge(swigCPtr, this, FeatureCollection.getCPtr(poFtCol), poFtCol, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Split(Geometry poSplitLine, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Split(swigCPtr, this, Geometry.getCPtr(poSplitLine), poSplitLine, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Dissolve(String pszAttrDescList, String pszStatisticsFields, boolean bUseMultiPart, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Dissolve(swigCPtr, this, pszAttrDescList, pszStatisticsFields, bUseMultiPart, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Generalize(double bTolerance, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Generalize(swigCPtr, this, bTolerance, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection PolygonGeneralize(double bTolerance, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_PolygonGeneralize(swigCPtr, this, bTolerance, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Densify(double dDistanceTolerance, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Densify(swigCPtr, this, dDistanceTolerance, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection RepairGeometry(boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_RepairGeometry(swigCPtr, this, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Fishnet(double dlExtMinX, double dlExtMinY, double dlExtMaxX, double dlExtMaxY, double dlUnitWidth, double dlUnitHeight, boolean bLineString, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Fishnet(swigCPtr, this, dlExtMinX, dlExtMinY, dlExtMaxX, dlExtMaxY, dlUnitWidth, dlUnitHeight, bLineString, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection DelaunayTriangulation(double dlTolerence, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_DelaunayTriangulation(swigCPtr, this, dlTolerence, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection ThiessenPolygon(double dlTolerence, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_ThiessenPolygon(swigCPtr, this, dlTolerence, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection FeaturesToPoint(String pszInside, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_FeaturesToPoint(swigCPtr, this, pszInside, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection FeatureVerticesToPoints(int ePointLocation, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_FeatureVerticesToPoints(swigCPtr, this, ePointLocation, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection MultipartToSinglepart(boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_MultipartToSinglepart(swigCPtr, this, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection RemoveHoles(boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_RemoveHoles(swigCPtr, this, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Project(SpatialReference poSrcSRS, SpatialReference poDecSRS, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Project(swigCPtr, this, SpatialReference.getCPtr(poSrcSRS), poSrcSRS, SpatialReference.getCPtr(poDecSRS), poDecSRS, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection MoveDistance(double dlLenX, double dlLenY, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_MoveDistance(swigCPtr, this, dlLenX, dlLenY, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection MoveAngle(double dlLength, int nAngle, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_MoveAngle(swigCPtr, this, dlLength, nAngle, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Rotate(double dlStandX, double dlStandY, int nAngle, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Rotate(swigCPtr, this, dlStandX, dlStandY, nAngle, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection Scale(double dlStandX, double dlStandY, double dlSX, double dlSY, boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_Scale(swigCPtr, this, dlStandX, dlStandY, dlSX, dlSY, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection LineToPolygon(boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_LineToPolygon(swigCPtr, this, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection PolygonToLine(boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_PolygonToLine(swigCPtr, this, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public FeatureCollection UnionLineMerge(boolean bNewFtCol) {
    long cPtr = jniJNI.FeatureCollection_UnionLineMerge(swigCPtr, this, bNewFtCol);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public void Group() {
    jniJNI.FeatureCollection_Group(swigCPtr, this);
  }

  public void Ungroup() {
    jniJNI.FeatureCollection_Ungroup(swigCPtr, this);
  }

  public void SetParameters(Parameters poParams) {
    jniJNI.FeatureCollection_SetParameters(swigCPtr, this, Parameters.getCPtr(poParams), poParams);
  }

}
