/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Feature {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Feature(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Feature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniJNI.delete_Feature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Feature obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Feature)
      equal = (((Feature)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.Feature_Destroy(swigCPtr, this);
  }

  public int SetGeometry(Geometry geom) {
    return jniJNI.Feature_SetGeometry(swigCPtr, this, Geometry.getCPtr(geom), geom);
  }

  public FeatureType GetFeatureType() {
    long cPtr = jniJNI.Feature_GetFeatureType(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureType(cPtr, false);
  }

  public FeatureCollection GetFeatureCollection() {
    long cPtr = jniJNI.Feature_GetFeatureCollection(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public Annotation GetAnnotation() {
    long cPtr = jniJNI.Feature_GetAnnotation(swigCPtr, this);
    return (cPtr == 0) ? null : new Annotation(cPtr, false);
  }

  public void SetAnnotation(Annotation anno) {
    jniJNI.Feature_SetAnnotation(swigCPtr, this, Annotation.getCPtr(anno), anno);
  }

  public long GetData() {
    return jniJNI.Feature_GetData(swigCPtr, this);
  }

  public void SetData(long data) {
    jniJNI.Feature_SetData(swigCPtr, this, data);
  }

  public boolean GetVisible() {
    return jniJNI.Feature_GetVisible(swigCPtr, this);
  }

  public void SetVisible(boolean bVal) {
    jniJNI.Feature_SetVisible(swigCPtr, this, bVal);
  }

  public boolean GetSelected() {
    return jniJNI.Feature_GetSelected(swigCPtr, this);
  }

  public void SetSelected(boolean bVal) {
    jniJNI.Feature_SetSelected(swigCPtr, this, bVal);
  }

  public Geometry GetAnnotationLine() {
    long cPtr = jniJNI.Feature_GetAnnotationLine(swigCPtr, this);
    return (cPtr == 0) ? null : new Geometry(cPtr, false);
  }

  public void SetAnnotationLine(Geometry geom) {
    jniJNI.Feature_SetAnnotationLine(swigCPtr, this, Geometry.getCPtr(geom), geom);
  }

  public boolean GetVisibleAnnotation() {
    return jniJNI.Feature_GetVisibleAnnotation(swigCPtr, this);
  }

  public void SetVisibleAnnotation(boolean bVal) {
    jniJNI.Feature_SetVisibleAnnotation(swigCPtr, this, bVal);
  }

  public boolean GetVisibleAnnotationLine() {
    return jniJNI.Feature_GetVisibleAnnotationLine(swigCPtr, this);
  }

  public void SetVisibleAnnotationLine(boolean bVal) {
    jniJNI.Feature_SetVisibleAnnotationLine(swigCPtr, this, bVal);
  }

  public UserDefinedWidget GetUserDefinedWidget() {
    long cPtr = jniJNI.Feature_GetUserDefinedWidget(swigCPtr, this);
    return (cPtr == 0) ? null : new UserDefinedWidget(cPtr, false);
  }

  public void SetUserDefinedWidget(UserDefinedWidget geom) {
    jniJNI.Feature_SetUserDefinedWidget(swigCPtr, this, UserDefinedWidget.getCPtr(geom), geom);
  }

  public boolean GetVisibleUserDefinedWidget() {
    return jniJNI.Feature_GetVisibleUserDefinedWidget(swigCPtr, this);
  }

  public void SetVisibleUserDefinedWidget(boolean bVal) {
    jniJNI.Feature_SetVisibleUserDefinedWidget(swigCPtr, this, bVal);
  }

  public GridCoverage GetGridCoverage() {
    long cPtr = jniJNI.Feature_GetGridCoverage(swigCPtr, this);
    return (cPtr == 0) ? null : new GridCoverage(cPtr, false);
  }

  public Geometry GetGeometry() {
    long cPtr = jniJNI.Feature_GetGeometry(swigCPtr, this);
    return (cPtr == 0) ? null : new Geometry(cPtr, false);
  }

  public Feature Clone() {
    long cPtr = jniJNI.Feature_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Feature(cPtr, true);
  }

  public String GetAttributeAsString(int id) {
    return jniJNI.Feature_GetAttributeAsString(swigCPtr, this, id);
  }

  public String GetAttributeToString(int id) {
    return jniJNI.Feature_GetAttributeToString(swigCPtr, this, id);
  }

  public String GetAttributeAsStringByName(String name) {
    return jniJNI.Feature_GetAttributeAsStringByName(swigCPtr, this, name);
  }

  public int GetAttributeAsInteger(int id) {
    return jniJNI.Feature_GetAttributeAsInteger(swigCPtr, this, id);
  }

  public double GetAttributeAsDouble(int id) {
    return jniJNI.Feature_GetAttributeAsDouble(swigCPtr, this, id);
  }

  public void GetAttributeAsDateTime(int id, int[] pnYear, int[] pnMonth, int[] pnDay, int[] pnHour, int[] pnMinute, int[] pnSecond, int[] pnTZFlag) {
    jniJNI.Feature_GetAttributeAsDateTime(swigCPtr, this, id, pnYear, pnMonth, pnDay, pnHour, pnMinute, pnSecond, pnTZFlag);
  }

  public int[] GetAttributeAsIntegerList(int id) {
    return jniJNI.Feature_GetAttributeAsIntegerList(swigCPtr, this, id);
  }

  public double[] GetAttributeAsDoubleList(int id) {
    return jniJNI.Feature_GetAttributeAsDoubleList(swigCPtr, this, id);
  }

  public String[] GetAttributeAsStringList(int id) {
    return jniJNI.Feature_GetAttributeAsStringList(swigCPtr, this, id);
  }

  public int GetFID() {
    return jniJNI.Feature_GetFID(swigCPtr, this);
  }

  public int SetFID(int fid) {
    return jniJNI.Feature_SetFID(swigCPtr, this, fid);
  }

  public int GetID() {
    return jniJNI.Feature_GetID(swigCPtr, this);
  }

  public void SetID(int fid) {
    jniJNI.Feature_SetID(swigCPtr, this, fid);
  }

  public void SetAttribute(int id, String value) {
    jniJNI.Feature_SetAttribute__SWIG_0(swigCPtr, this, id, value);
  }

  public void SetAttribute(String name, String value) {
    jniJNI.Feature_SetAttribute__SWIG_1(swigCPtr, this, name, value);
  }

  public void SetAttribute(int id, int value) {
    jniJNI.Feature_SetAttribute__SWIG_2(swigCPtr, this, id, value);
  }

  public void SetAttribute(String name, int value) {
    jniJNI.Feature_SetAttribute__SWIG_3(swigCPtr, this, name, value);
  }

  public void SetAttribute(int id, double value) {
    jniJNI.Feature_SetAttribute__SWIG_4(swigCPtr, this, id, value);
  }

  public void SetAttribute(String name, double value) {
    jniJNI.Feature_SetAttribute__SWIG_5(swigCPtr, this, name, value);
  }

  public void SetAttribute(int id, int year, int month, int day, int hour, int minute, int second, int tzflag) {
    jniJNI.Feature_SetAttribute__SWIG_6(swigCPtr, this, id, year, month, day, hour, minute, second, tzflag);
  }

  public void SetAttribute(String name, int year, int month, int day, int hour, int minute, int second, int tzflag) {
    jniJNI.Feature_SetAttribute__SWIG_7(swigCPtr, this, name, year, month, day, hour, minute, second, tzflag);
  }

  public void SetAttributeIntegerList(int id, int[] nList) {
    jniJNI.Feature_SetAttributeIntegerList(swigCPtr, this, id, nList);
  }

  public void SetAttributeDoubleList(int id, double[] nList) {
    jniJNI.Feature_SetAttributeDoubleList(swigCPtr, this, id, nList);
  }

  public void SetAttributeStringList(int id, java.util.Vector pList) {
    jniJNI.Feature_SetAttributeStringList(swigCPtr, this, id, pList);
  }

  public void SetSymbolizer(Symbolizer h) {
    jniJNI.Feature_SetSymbolizer(swigCPtr, this, Symbolizer.getCPtr(h), h);
  }

  public Symbolizer GetSymbolizer() {
    long cPtr = jniJNI.Feature_GetSymbolizer(swigCPtr, this);
    return (cPtr == 0) ? null : new Symbolizer(cPtr, false);
  }

}
