/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class FeatureLayer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FeatureLayer(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(FeatureLayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(FeatureLayer obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof FeatureLayer)
      equal = (((FeatureLayer)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.FeatureLayer_Destroy(swigCPtr, this);
  }

  public FeatureCanvas GetFeatureCanvas() {
    long cPtr = jniJNI.FeatureLayer_GetFeatureCanvas(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureCanvas(cPtr, false);
  }

  public FeatureCollection GetFeatureCollection() {
    long cPtr = jniJNI.FeatureLayer_GetFeatureCollection(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public void SetFeatureCollection(FeatureCollection h) {
    jniJNI.FeatureLayer_SetFeatureCollection(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public Layer GetLayer() {
    long cPtr = jniJNI.FeatureLayer_GetLayer(swigCPtr, this);
    return (cPtr == 0) ? null : new Layer(cPtr, false);
  }

  public LayerSource GetLayerSource() {
    long cPtr = jniJNI.FeatureLayer_GetLayerSource(swigCPtr, this);
    return (cPtr == 0) ? null : new LayerSource(cPtr, false);
  }

  public boolean Export(LayerSource oLayerSrc, String pszDstName, java.util.Vector papszSelFields, boolean bAppend, int eGType, boolean bOverwrite, boolean bTransform, SpatialReference pszSourceSRS, SpatialReference pszOutputSRS, String pszFilter, boolean bOnlySelected, int nMapIndex, String pszOptions) {
    return jniJNI.FeatureLayer_Export(swigCPtr, this, LayerSource.getCPtr(oLayerSrc), oLayerSrc, pszDstName, papszSelFields, bAppend, eGType, bOverwrite, bTransform, SpatialReference.getCPtr(pszSourceSRS), pszSourceSRS, SpatialReference.getCPtr(pszOutputSRS), pszOutputSRS, pszFilter, bOnlySelected, nMapIndex, pszOptions);
  }

  public FeatureAttributeDescriptor AddAttribute(FeatureAttributeDescriptor h) {
    long cPtr = jniJNI.FeatureLayer_AddAttribute(swigCPtr, this, FeatureAttributeDescriptor.getCPtr(h), h);
    return (cPtr == 0) ? null : new FeatureAttributeDescriptor(cPtr, false);
  }

  public int RemoveAttribute(int index) {
    return jniJNI.FeatureLayer_RemoveAttribute(swigCPtr, this, index);
  }

  public FeatureAttributeDescriptor SetAttribute(int index, FeatureAttributeDescriptor h) {
    long cPtr = jniJNI.FeatureLayer_SetAttribute(swigCPtr, this, index, FeatureAttributeDescriptor.getCPtr(h), h);
    return (cPtr == 0) ? null : new FeatureAttributeDescriptor(cPtr, false);
  }

  public String GetDriverType() {
    return jniJNI.FeatureLayer_GetDriverType(swigCPtr, this);
  }

  public void ShowStyleWidget() {
    jniJNI.FeatureLayer_ShowStyleWidget(swigCPtr, this);
  }

  public void ShowTypeStyleWidget() {
    jniJNI.FeatureLayer_ShowTypeStyleWidget(swigCPtr, this);
  }

  public void ShowLabelWidget() {
    jniJNI.FeatureLayer_ShowLabelWidget(swigCPtr, this);
  }

  public void ShowExportLayerWidget() {
    jniJNI.FeatureLayer_ShowExportLayerWidget(swigCPtr, this);
  }

  public void SetRefreshTime(String pszFieldList, String pszCheckTimeField, int bIncludeSystemField, int nRefreshTerm) {
    jniJNI.FeatureLayer_SetRefreshTime(swigCPtr, this, pszFieldList, pszCheckTimeField, bIncludeSystemField, nRefreshTerm);
  }

  public boolean Refresh() {
    return jniJNI.FeatureLayer_Refresh(swigCPtr, this);
  }

}
