/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Parameter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Parameter(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Parameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Parameter obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Parameter)
      equal = (((Parameter)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.Parameter_Destroy(swigCPtr, this);
  }

  public Parameter GetParent() {
    long cPtr = jniJNI.Parameter_GetParent(swigCPtr, this);
    return (cPtr == 0) ? null : new Parameter(cPtr, false);
  }

  public void SetParent(Parameter param) {
    jniJNI.Parameter_SetParent(swigCPtr, this, Parameter.getCPtr(param), param);
  }

  public String GetName() {
    return jniJNI.Parameter_GetName(swigCPtr, this);
  }

  public void SetName(String name) {
    jniJNI.Parameter_SetName(swigCPtr, this, name);
  }

  public Parameter Clone() {
    long cPtr = jniJNI.Parameter_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Parameter(cPtr, false);
  }

  public void Clear() {
    jniJNI.Parameter_Clear(swigCPtr, this);
  }

  public boolean GetBool() {
    return jniJNI.Parameter_GetBool(swigCPtr, this);
  }

  public void SetBool(boolean b) {
    jniJNI.Parameter_SetBool(swigCPtr, this, b);
  }

  public int GetInt() {
    return jniJNI.Parameter_GetInt(swigCPtr, this);
  }

  public void SetInt(int i) {
    jniJNI.Parameter_SetInt(swigCPtr, this, i);
  }

  public short GetShort() {
    return jniJNI.Parameter_GetShort(swigCPtr, this);
  }

  public void SetShort(short s) {
    jniJNI.Parameter_SetShort(swigCPtr, this, s);
  }

  public int GetLong() {
    return jniJNI.Parameter_GetLong(swigCPtr, this);
  }

  public void SetLong(int l) {
    jniJNI.Parameter_SetLong(swigCPtr, this, l);
  }

  public float GetFloat() {
    return jniJNI.Parameter_GetFloat(swigCPtr, this);
  }

  public void SetFloat(float f) {
    jniJNI.Parameter_SetFloat(swigCPtr, this, f);
  }

  public double GetDouble() {
    return jniJNI.Parameter_GetDouble(swigCPtr, this);
  }

  public void SetDouble(double d) {
    jniJNI.Parameter_SetDouble(swigCPtr, this, d);
  }

  public String GetString() {
    return jniJNI.Parameter_GetString(swigCPtr, this);
  }

  public void SetString(String pStr) {
    jniJNI.Parameter_SetString(swigCPtr, this, pStr);
  }

  public FeatureCollection GetFeatureCollection() {
    long cPtr = jniJNI.Parameter_GetFeatureCollection(swigCPtr, this);
    return (cPtr == 0) ? null : new FeatureCollection(cPtr, false);
  }

  public void SetFeatureCollection(FeatureCollection h) {
    jniJNI.Parameter_SetFeatureCollection(swigCPtr, this, FeatureCollection.getCPtr(h), h);
  }

  public GridCoverage GetGridCoverage() {
    long cPtr = jniJNI.Parameter_GetGridCoverage(swigCPtr, this);
    return (cPtr == 0) ? null : new GridCoverage(cPtr, false);
  }

  public void SetGridCoverage(GridCoverage h) {
    jniJNI.Parameter_SetGridCoverage(swigCPtr, this, GridCoverage.getCPtr(h), h);
  }

}
