/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Sensor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Sensor(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Sensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Sensor obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Sensor)
      equal = (((Sensor)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public boolean Start(Parameters pdspParam) {
    return jniJNI.Sensor_Start(swigCPtr, this, Parameters.getCPtr(pdspParam), pdspParam);
  }

  public void Stop() {
    jniJNI.Sensor_Stop(swigCPtr, this);
  }

  public boolean IsServiceRunning() {
    return jniJNI.Sensor_IsServiceRunning(swigCPtr, this);
  }

  public void AddEventListener(Event h) {
    jniJNI.Sensor_AddEventListener(swigCPtr, this, Event.getCPtr(h), h);
  }

  public void RemoveEventListener(Event h) {
    jniJNI.Sensor_RemoveEventListener(swigCPtr, this, Event.getCPtr(h), h);
  }

  public boolean HasEventListener(Event h) {
    return jniJNI.Sensor_HasEventListener(swigCPtr, this, Event.getCPtr(h), h);
  }

  public String GetLatestValueToXML() {
    return jniJNI.Sensor_GetLatestValueToXML(swigCPtr, this);
  }

}
