/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class UserDefinedWidget extends Widget {
  private long swigCPtr;

  protected UserDefinedWidget(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.UserDefinedWidget_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UserDefinedWidget obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(UserDefinedWidget obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof UserDefinedWidget)
      equal = (((UserDefinedWidget)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public int GetPosition() {
    return jniJNI.UserDefinedWidget_GetPosition(swigCPtr, this);
  }

  public void SetPosition(int eType) {
    jniJNI.UserDefinedWidget_SetPosition(swigCPtr, this, eType);
  }

  public int GetRelateX() {
    return jniJNI.UserDefinedWidget_GetRelateX(swigCPtr, this);
  }

  public void SetRelateX(int val) {
    jniJNI.UserDefinedWidget_SetRelateX(swigCPtr, this, val);
  }

  public int GetRelateY() {
    return jniJNI.UserDefinedWidget_GetRelateY(swigCPtr, this);
  }

  public void SetRelateY(int val) {
    jniJNI.UserDefinedWidget_SetRelateY(swigCPtr, this, val);
  }

  public int IsExteriorHandle() {
    return jniJNI.UserDefinedWidget_IsExteriorHandle(swigCPtr, this);
  }

  public void SetExteriorHandle(boolean val) {
    jniJNI.UserDefinedWidget_SetExteriorHandle(swigCPtr, this, val);
  }

}
