/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class AnnotationLabel extends Feature {
  private long swigCPtr;

  protected AnnotationLabel(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.AnnotationLabel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnnotationLabel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(AnnotationLabel obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof AnnotationLabel)
      equal = (((AnnotationLabel)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public Layer GetLayer() {
    long cPtr = jniJNI.AnnotationLabel_GetLayer(swigCPtr, this);
    return (cPtr == 0) ? null : new Layer(cPtr, false);
  }

  public void SetLayer(Layer layer) {
    jniJNI.AnnotationLabel_SetLayer(swigCPtr, this, Layer.getCPtr(layer), layer);
  }

  public String GetText() {
    return jniJNI.AnnotationLabel_GetText(swigCPtr, this);
  }

  public void SetText(String text) {
    jniJNI.AnnotationLabel_SetText(swigCPtr, this, text);
  }

  public int GetOrder() {
    return jniJNI.AnnotationLabel_GetOrder(swigCPtr, this);
  }

  public void SetOrder(int order) {
    jniJNI.AnnotationLabel_SetOrder(swigCPtr, this, order);
  }

}
