/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class ColorRampList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ColorRampList(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(ColorRampList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(ColorRampList obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof ColorRampList)
      equal = (((ColorRampList)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public int GetSize() {
    return jniJNI.ColorRampList_GetSize(swigCPtr, this);
  }

  public String GetName(int index) {
    return jniJNI.ColorRampList_GetName(swigCPtr, this, index);
  }

  public GridColorRampStyle GetColorRamp(int index) {
    long cPtr = jniJNI.ColorRampList_GetColorRamp(swigCPtr, this, index);
    return (cPtr == 0) ? null : new GridColorRampStyle(cPtr, false);
  }

  public GridColorRampStyle GetColorRampByName(String pszName) {
    long cPtr = jniJNI.ColorRampList_GetColorRampByName(swigCPtr, this, pszName);
    return (cPtr == 0) ? null : new GridColorRampStyle(cPtr, false);
  }

  public int AddColorRamp(String pszTitle, GridColorRampStyle newStyle) {
    return jniJNI.ColorRampList_AddColorRamp(swigCPtr, this, pszTitle, GridColorRampStyle.getCPtr(newStyle), newStyle);
  }

  public void RemoveColorRamp(String pszTitle) {
    jniJNI.ColorRampList_RemoveColorRamp(swigCPtr, this, pszTitle);
  }

}
