/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GeographicTransform {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GeographicTransform(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(GeographicTransform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniJNI.delete_GeographicTransform(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GeographicTransform obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GeographicTransform)
      equal = (((GeographicTransform)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public SpatialReference GetSourceCS() {
    long cPtr = jniJNI.GeographicTransform_GetSourceCS(swigCPtr, this);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

  public SpatialReference GetTargetCS() {
    long cPtr = jniJNI.GeographicTransform_GetTargetCS(swigCPtr, this);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, false);
  }

  public void SetSourceCS(SpatialReference crs) {
    jniJNI.GeographicTransform_SetSourceCS(swigCPtr, this, SpatialReference.getCPtr(crs), crs);
  }

  public void SetTargetCS(SpatialReference crs) {
    jniJNI.GeographicTransform_SetTargetCS(swigCPtr, this, SpatialReference.getCPtr(crs), crs);
  }

  public void Forward(Geometry geom) {
    jniJNI.GeographicTransform_Forward(swigCPtr, this, Geometry.getCPtr(geom), geom);
  }

  public void Inverse(Geometry geom) {
    jniJNI.GeographicTransform_Inverse(swigCPtr, this, Geometry.getCPtr(geom), geom);
  }

  public int Transform(double[][] nCount) {
    return jniJNI.GeographicTransform_Transform(swigCPtr, this, nCount);
  }

}
