/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GraphicArc extends Graphic {
  private long swigCPtr;

  protected GraphicArc(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.GraphicArc_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GraphicArc obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GraphicArc obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GraphicArc)
      equal = (((GraphicArc)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetCenter(float x, float y) {
    jniJNI.GraphicArc_SetCenter(swigCPtr, this, x, y);
  }

  public void GetCenter(SWIGTYPE_p_float x, SWIGTYPE_p_float y) {
    jniJNI.GraphicArc_GetCenter(swigCPtr, this, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y));
  }

  public void SetWidth(float w) {
    jniJNI.GraphicArc_SetWidth(swigCPtr, this, w);
  }

  public float GetWidth() {
    return jniJNI.GraphicArc_GetWidth(swigCPtr, this);
  }

  public void SetHeight(float h) {
    jniJNI.GraphicArc_SetHeight(swigCPtr, this, h);
  }

  public float GetHeight() {
    return jniJNI.GraphicArc_GetHeight(swigCPtr, this);
  }

  public void SetStart(float a) {
    jniJNI.GraphicArc_SetStart(swigCPtr, this, a);
  }

  public float GetStart() {
    return jniJNI.GraphicArc_GetStart(swigCPtr, this);
  }

  public void SetEnd(float a) {
    jniJNI.GraphicArc_SetEnd__SWIG_0(swigCPtr, this, a);
  }

  public float GetEnd() {
    return jniJNI.GraphicArc_GetEnd(swigCPtr, this);
  }

  public boolean IsCircle() {
    return jniJNI.GraphicArc_IsCircle(swigCPtr, this);
  }

  public boolean IsClosedEllipse() {
    return jniJNI.GraphicArc_IsClosedEllipse(swigCPtr, this);
  }

  public boolean IsAllowingExtentsChang() {
    return jniJNI.GraphicArc_IsAllowingExtentsChang(swigCPtr, this);
  }

  public void SetEnd(boolean a) {
    jniJNI.GraphicArc_SetEnd__SWIG_1(swigCPtr, this, a);
  }

}
