/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GraphicLabel extends Graphic {
  private long swigCPtr;

  protected GraphicLabel(long cPtr, boolean cMemoryOwn) {
    super(jniJNI.GraphicLabel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GraphicLabel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GraphicLabel obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GraphicLabel)
      equal = (((GraphicLabel)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetText(String pszTxt) {
    jniJNI.GraphicLabel_SetText(swigCPtr, this, pszTxt);
  }

  public String GetText() {
    return jniJNI.GraphicLabel_GetText__SWIG_0(swigCPtr, this);
  }

  public void SetTextSize(int nSize) {
    jniJNI.GraphicLabel_SetTextSize(swigCPtr, this, nSize);
  }

  public int GetTextSize() {
    return jniJNI.GraphicLabel_GetTextSize(swigCPtr, this);
  }

  public void SetPosition(float x, float y) {
    jniJNI.GraphicLabel_SetPosition(swigCPtr, this, x, y);
  }

  public void GetText(SWIGTYPE_p_float x, SWIGTYPE_p_float y) {
    jniJNI.GraphicLabel_GetText__SWIG_1(swigCPtr, this, SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y));
  }

  public void SetXAnchor(int anchor) {
    jniJNI.GraphicLabel_SetXAnchor(swigCPtr, this, anchor);
  }

  public int GetXAnchor() {
    return jniJNI.GraphicLabel_GetXAnchor(swigCPtr, this);
  }

  public void SetYAnchor(int anchor) {
    jniJNI.GraphicLabel_SetYAnchor(swigCPtr, this, anchor);
  }

  public int GetYAnchor() {
    return jniJNI.GraphicLabel_GetYAnchor(swigCPtr, this);
  }

}
