/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class GridOperation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GridOperation(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(GridOperation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(GridOperation obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof GridOperation)
      equal = (((GridOperation)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void SetName(String name) {
    jniJNI.GridOperation_SetName(swigCPtr, this, name);
  }

  public String GetName() {
    return jniJNI.GridOperation_GetName(swigCPtr, this);
  }

  public void SetDescription(String pStr) {
    jniJNI.GridOperation_SetDescription(swigCPtr, this, pStr);
  }

  public String GetDescription() {
    return jniJNI.GridOperation_GetDescription(swigCPtr, this);
  }

  public void SetVendor(String pStr) {
    jniJNI.GridOperation_SetVendor(swigCPtr, this, pStr);
  }

  public String GetVendor() {
    return jniJNI.GridOperation_GetVendor(swigCPtr, this);
  }

  public void SetUrl(String pStr) {
    jniJNI.GridOperation_SetUrl(swigCPtr, this, pStr);
  }

  public String GetUrl() {
    return jniJNI.GridOperation_GetUrl(swigCPtr, this);
  }

  public void SetVersion(String pStr) {
    jniJNI.GridOperation_SetVersion(swigCPtr, this, pStr);
  }

  public String GetVersion() {
    return jniJNI.GridOperation_GetVersion(swigCPtr, this);
  }

  public void SetSourceNum(int num) {
    jniJNI.GridOperation_SetSourceNum(swigCPtr, this, num);
  }

  public int GetSourceNum() {
    return jniJNI.GridOperation_GetSourceNum(swigCPtr, this);
  }

  public void SetParamNum(int l) {
    jniJNI.GridOperation_SetParamNum(swigCPtr, this, l);
  }

  public int GetParamNum() {
    return jniJNI.GridOperation_GetParamNum(swigCPtr, this);
  }

  public ParameterInfo GetParameterInfo(int num) {
    long cPtr = jniJNI.GridOperation_GetParameterInfo(swigCPtr, this, num);
    return (cPtr == 0) ? null : new ParameterInfo(cPtr, false);
  }

}
