/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class Parameters {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Parameters(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0)
        throw new RuntimeException();
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(Parameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  private Object parentReference;

  protected static long getCPtrAndDisown(Parameters obj) {
    if (obj != null)
    {
        obj.swigCMemOwn= false;
        obj.parentReference = null;
    }
    return getCPtr(obj);
  }

  /* Ensure that the GC doesn't collect any parent instance set from Java */
  protected void addReference(Object reference) {
    parentReference = reference;
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof Parameters)
      equal = (((Parameters)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public int hashCode() {
     return (int)swigCPtr;
  }


  public void Destroy() {
    jniJNI.Parameters_Destroy(swigCPtr, this);
  }

  public int GetSize() {
    return jniJNI.Parameters_GetSize(swigCPtr, this);
  }

  public Parameter GetParameter(String pStr) {
    long cPtr = jniJNI.Parameters_GetParameter(swigCPtr, this, pStr);
    return (cPtr == 0) ? null : new Parameter(cPtr, false);
  }

  public void AddParameter(Parameter poParam, Parameter poParent) {
    jniJNI.Parameters_AddParameter(swigCPtr, this, Parameter.getCPtr(poParam), poParam, Parameter.getCPtr(poParent), poParent);
  }

}
