/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.sgsrc.map.jni;

public class SpatialReference implements Cloneable {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public SpatialReference(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }
  
  public static long getCPtr(SpatialReference obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniJNI.delete_SpatialReference(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
    boolean equal = false;
    if (obj instanceof SpatialReference)
      equal = (((SpatialReference)obj).swigCPtr == this.swigCPtr);
    return equal;
  }

  public Object clone()
  {
      return Clone();
  }

  public int hashCode() {
     return (int)swigCPtr;
  }

  public String toString() {
    return __str__();
  }

  public String ExportToWkt() {
    String array[] = new String[] {null};
    ExportToWkt(array);
    return array[0];
  }

  public String ExportToPrettyWkt(int simplify) {
    String array[] = new String[] {null};
    ExportToPrettyWkt(array, simplify);
    return array[0];
  }

  public String ExportToPrettyWkt() {
    String array[] = new String[] {null};
    ExportToPrettyWkt(array);
    return array[0];
  }

  public String ExportToProj4() {
    String array[] = new String[] {null};
    ExportToProj4(array);
    return array[0];
  }

  public String ExportToXML( String dialect) {
    String array[] = new String[] {null};
    ExportToXML(array, dialect);
    return array[0];
  }

  public String ExportToXML() {
    String array[] = new String[] {null};
    ExportToXML(array);
    return array[0];
  }

  public String ExportToMICoordSys() {
    String array[] = new String[] {null};
    ExportToMICoordSys(array);
    return array[0];
  }

  public double[] GetTOWGS84()
  {
      double array[] = new double[7];
      GetTOWGS84(array);
      return array;
  }
  
  public int SetTOWGS84( double p1, double p2, double p3)
  {
      return SetTOWGS84(p1, p2, p3, 0, 0, 0, 0);
  }

  public SpatialReference(String wkt) {
    this(jniJNI.new_SpatialReference__SWIG_0(wkt), true);
  }

  public SpatialReference() {
    this(jniJNI.new_SpatialReference__SWIG_1(), true);
  }

  public void Destroy() {
    jniJNI.SpatialReference_Destroy(swigCPtr, this);
  }

  public String __str__() {
    return jniJNI.SpatialReference___str__(swigCPtr, this);
  }

  public int IsSame(SpatialReference rhs) {
    return jniJNI.SpatialReference_IsSame(swigCPtr, this, SpatialReference.getCPtr(rhs), rhs);
  }

  public int IsSameGeogCS(SpatialReference rhs) {
    return jniJNI.SpatialReference_IsSameGeogCS(swigCPtr, this, SpatialReference.getCPtr(rhs), rhs);
  }

  public int IsGeographic() {
    return jniJNI.SpatialReference_IsGeographic(swigCPtr, this);
  }

  public int IsProjected() {
    return jniJNI.SpatialReference_IsProjected(swigCPtr, this);
  }

  public int IsLocal() {
    return jniJNI.SpatialReference_IsLocal(swigCPtr, this);
  }

  public int EPSGTreatsAsLatLong() {
    return jniJNI.SpatialReference_EPSGTreatsAsLatLong(swigCPtr, this);
  }

  public int SetAuthority(String pszTargetKey, String pszAuthority, int nCode) {
    return jniJNI.SpatialReference_SetAuthority(swigCPtr, this, pszTargetKey, pszAuthority, nCode);
  }

  public String GetAttrValue(String name, int child) {
    return jniJNI.SpatialReference_GetAttrValue__SWIG_0(swigCPtr, this, name, child);
  }

  public String GetAttrValue(String name) {
    return jniJNI.SpatialReference_GetAttrValue__SWIG_1(swigCPtr, this, name);
  }

  public int SetAttrValue(String name, String value) {
    return jniJNI.SpatialReference_SetAttrValue(swigCPtr, this, name, value);
  }

  public int SetAngularUnits(String name, double to_radians) {
    return jniJNI.SpatialReference_SetAngularUnits(swigCPtr, this, name, to_radians);
  }

  public double GetAngularUnits() {
    return jniJNI.SpatialReference_GetAngularUnits(swigCPtr, this);
  }

  public int SetLinearUnits(String name, double to_meters) {
    return jniJNI.SpatialReference_SetLinearUnits(swigCPtr, this, name, to_meters);
  }

  public int SetLinearUnitsAndUpdateParameters(String name, double to_meters) {
    return jniJNI.SpatialReference_SetLinearUnitsAndUpdateParameters(swigCPtr, this, name, to_meters);
  }

  public double GetLinearUnits() {
    return jniJNI.SpatialReference_GetLinearUnits(swigCPtr, this);
  }

  public String GetLinearUnitsName() {
    return jniJNI.SpatialReference_GetLinearUnitsName(swigCPtr, this);
  }

  public String GetAuthorityCode(String target_key) {
    return jniJNI.SpatialReference_GetAuthorityCode(swigCPtr, this, target_key);
  }

  public String GetAuthorityName(String target_key) {
    return jniJNI.SpatialReference_GetAuthorityName(swigCPtr, this, target_key);
  }

  public int SetUTM(int zone, int north) {
    return jniJNI.SpatialReference_SetUTM__SWIG_0(swigCPtr, this, zone, north);
  }

  public int SetUTM(int zone) {
    return jniJNI.SpatialReference_SetUTM__SWIG_1(swigCPtr, this, zone);
  }

  public int GetUTMZone() {
    return jniJNI.SpatialReference_GetUTMZone(swigCPtr, this);
  }

  public int SetStatePlane(int zone, int is_nad83, String unitsname, double units) {
    return jniJNI.SpatialReference_SetStatePlane__SWIG_0(swigCPtr, this, zone, is_nad83, unitsname, units);
  }

  public int SetStatePlane(int zone, int is_nad83, String unitsname) {
    return jniJNI.SpatialReference_SetStatePlane__SWIG_1(swigCPtr, this, zone, is_nad83, unitsname);
  }

  public int SetStatePlane(int zone, int is_nad83) {
    return jniJNI.SpatialReference_SetStatePlane__SWIG_2(swigCPtr, this, zone, is_nad83);
  }

  public int SetStatePlane(int zone) {
    return jniJNI.SpatialReference_SetStatePlane__SWIG_3(swigCPtr, this, zone);
  }

  public int AutoIdentifyEPSG() {
    return jniJNI.SpatialReference_AutoIdentifyEPSG(swigCPtr, this);
  }

  public int SetProjection(String arg) {
    return jniJNI.SpatialReference_SetProjection(swigCPtr, this, arg);
  }

  public int SetProjParm(String name, double val) {
    return jniJNI.SpatialReference_SetProjParm(swigCPtr, this, name, val);
  }

  public double GetProjParm(String name, double default_val) {
    return jniJNI.SpatialReference_GetProjParm__SWIG_0(swigCPtr, this, name, default_val);
  }

  public double GetProjParm(String name) {
    return jniJNI.SpatialReference_GetProjParm__SWIG_1(swigCPtr, this, name);
  }

  public int SetNormProjParm(String name, double val) {
    return jniJNI.SpatialReference_SetNormProjParm(swigCPtr, this, name, val);
  }

  public double GetNormProjParm(String name, double default_val) {
    return jniJNI.SpatialReference_GetNormProjParm__SWIG_0(swigCPtr, this, name, default_val);
  }

  public double GetNormProjParm(String name) {
    return jniJNI.SpatialReference_GetNormProjParm__SWIG_1(swigCPtr, this, name);
  }

  public double GetSemiMajor() {
    return jniJNI.SpatialReference_GetSemiMajor(swigCPtr, this);
  }

  public double GetSemiMinor() {
    return jniJNI.SpatialReference_GetSemiMinor(swigCPtr, this);
  }

  public double GetInvFlattening() {
    return jniJNI.SpatialReference_GetInvFlattening(swigCPtr, this);
  }

  public int SetACEA(double stdp1, double stdp2, double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetACEA(swigCPtr, this, stdp1, stdp2, clat, clong, fe, fn);
  }

  public int SetAE(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetAE(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetBonne(double stdp, double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetBonne(swigCPtr, this, stdp, cm, fe, fn);
  }

  public int SetCEA(double stdp1, double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetCEA(swigCPtr, this, stdp1, cm, fe, fn);
  }

  public int SetCS(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetCS(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetEC(double stdp1, double stdp2, double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetEC(swigCPtr, this, stdp1, stdp2, clat, clong, fe, fn);
  }

  public int SetEckertIV(double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetEckertIV(swigCPtr, this, cm, fe, fn);
  }

  public int SetEckertVI(double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetEckertVI(swigCPtr, this, cm, fe, fn);
  }

  public int SetEquirectangular(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetEquirectangular(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetEquirectangular2(double clat, double clong, double pseudostdparallellat, double fe, double fn) {
    return jniJNI.SpatialReference_SetEquirectangular2(swigCPtr, this, clat, clong, pseudostdparallellat, fe, fn);
  }

  public int SetGaussSchreiberTMercator(double clat, double clong, double sc, double fe, double fn) {
    return jniJNI.SpatialReference_SetGaussSchreiberTMercator(swigCPtr, this, clat, clong, sc, fe, fn);
  }

  public int SetGS(double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetGS(swigCPtr, this, cm, fe, fn);
  }

  public int SetGH(double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetGH(swigCPtr, this, cm, fe, fn);
  }

  public int SetGEOS(double cm, double satelliteheight, double fe, double fn) {
    return jniJNI.SpatialReference_SetGEOS(swigCPtr, this, cm, satelliteheight, fe, fn);
  }

  public int SetGnomonic(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetGnomonic(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetHOM(double clat, double clong, double azimuth, double recttoskew, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetHOM(swigCPtr, this, clat, clong, azimuth, recttoskew, scale, fe, fn);
  }

  public int SetHOM2PNO(double clat, double dfLat1, double dfLong1, double dfLat2, double dfLong2, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetHOM2PNO(swigCPtr, this, clat, dfLat1, dfLong1, dfLat2, dfLong2, scale, fe, fn);
  }

  public int SetKrovak(double clat, double clong, double azimuth, double pseudostdparallellat, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetKrovak(swigCPtr, this, clat, clong, azimuth, pseudostdparallellat, scale, fe, fn);
  }

  public int SetLAEA(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetLAEA(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetLCC(double stdp1, double stdp2, double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetLCC(swigCPtr, this, stdp1, stdp2, clat, clong, fe, fn);
  }

  public int SetLCC1SP(double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetLCC1SP(swigCPtr, this, clat, clong, scale, fe, fn);
  }

  public int SetLCCB(double stdp1, double stdp2, double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetLCCB(swigCPtr, this, stdp1, stdp2, clat, clong, fe, fn);
  }

  public int SetMC(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetMC(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetMercator(double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetMercator(swigCPtr, this, clat, clong, scale, fe, fn);
  }

  public int SetMollweide(double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetMollweide(swigCPtr, this, cm, fe, fn);
  }

  public int SetNZMG(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetNZMG(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetOS(double dfOriginLat, double dfCMeridian, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetOS(swigCPtr, this, dfOriginLat, dfCMeridian, scale, fe, fn);
  }

  public int SetOrthographic(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetOrthographic(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetPolyconic(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetPolyconic(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetPS(double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetPS(swigCPtr, this, clat, clong, scale, fe, fn);
  }

  public int SetRobinson(double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetRobinson(swigCPtr, this, clong, fe, fn);
  }

  public int SetSinusoidal(double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetSinusoidal(swigCPtr, this, clong, fe, fn);
  }

  public int SetStereographic(double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetStereographic(swigCPtr, this, clat, clong, scale, fe, fn);
  }

  public int SetSOC(double latitudeoforigin, double cm, double fe, double fn) {
    return jniJNI.SpatialReference_SetSOC(swigCPtr, this, latitudeoforigin, cm, fe, fn);
  }

  public int SetTM(double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetTM(swigCPtr, this, clat, clong, scale, fe, fn);
  }

  public int SetTMVariant(String pszVariantName, double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetTMVariant(swigCPtr, this, pszVariantName, clat, clong, scale, fe, fn);
  }

  public int SetTMG(double clat, double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetTMG(swigCPtr, this, clat, clong, fe, fn);
  }

  public int SetTMSO(double clat, double clong, double scale, double fe, double fn) {
    return jniJNI.SpatialReference_SetTMSO(swigCPtr, this, clat, clong, scale, fe, fn);
  }

  public int SetVDG(double clong, double fe, double fn) {
    return jniJNI.SpatialReference_SetVDG(swigCPtr, this, clong, fe, fn);
  }

  public int SetWellKnownGeogCS(String name) {
    return jniJNI.SpatialReference_SetWellKnownGeogCS(swigCPtr, this, name);
  }

  public int SetFromUserInput(String name) {
    return jniJNI.SpatialReference_SetFromUserInput(swigCPtr, this, name);
  }

  public int CopyGeogCSFrom(SpatialReference rhs) {
    return jniJNI.SpatialReference_CopyGeogCSFrom(swigCPtr, this, SpatialReference.getCPtr(rhs), rhs);
  }

  public int SetTOWGS84(double p1, double p2, double p3, double p4, double p5, double p6, double p7) {
    return jniJNI.SpatialReference_SetTOWGS84(swigCPtr, this, p1, p2, p3, p4, p5, p6, p7);
  }

  public int GetTOWGS84(double[] argout) {
    return jniJNI.SpatialReference_GetTOWGS84(swigCPtr, this, argout);
  }

  public int SetLocalCS(String pszName) {
    return jniJNI.SpatialReference_SetLocalCS(swigCPtr, this, pszName);
  }

  public int SetGeogCS(String pszGeogName, String pszDatumName, String pszEllipsoidName, double dfSemiMajor, double dfInvFlattening, String pszPMName, double dfPMOffset, String pszUnits, double dfConvertToRadians) {
    return jniJNI.SpatialReference_SetGeogCS__SWIG_0(swigCPtr, this, pszGeogName, pszDatumName, pszEllipsoidName, dfSemiMajor, dfInvFlattening, pszPMName, dfPMOffset, pszUnits, dfConvertToRadians);
  }

  public int SetGeogCS(String pszGeogName, String pszDatumName, String pszEllipsoidName, double dfSemiMajor, double dfInvFlattening, String pszPMName, double dfPMOffset, String pszUnits) {
    return jniJNI.SpatialReference_SetGeogCS__SWIG_1(swigCPtr, this, pszGeogName, pszDatumName, pszEllipsoidName, dfSemiMajor, dfInvFlattening, pszPMName, dfPMOffset, pszUnits);
  }

  public int SetGeogCS(String pszGeogName, String pszDatumName, String pszEllipsoidName, double dfSemiMajor, double dfInvFlattening, String pszPMName, double dfPMOffset) {
    return jniJNI.SpatialReference_SetGeogCS__SWIG_2(swigCPtr, this, pszGeogName, pszDatumName, pszEllipsoidName, dfSemiMajor, dfInvFlattening, pszPMName, dfPMOffset);
  }

  public int SetGeogCS(String pszGeogName, String pszDatumName, String pszEllipsoidName, double dfSemiMajor, double dfInvFlattening, String pszPMName) {
    return jniJNI.SpatialReference_SetGeogCS__SWIG_3(swigCPtr, this, pszGeogName, pszDatumName, pszEllipsoidName, dfSemiMajor, dfInvFlattening, pszPMName);
  }

  public int SetGeogCS(String pszGeogName, String pszDatumName, String pszEllipsoidName, double dfSemiMajor, double dfInvFlattening) {
    return jniJNI.SpatialReference_SetGeogCS__SWIG_4(swigCPtr, this, pszGeogName, pszDatumName, pszEllipsoidName, dfSemiMajor, dfInvFlattening);
  }

  public int SetProjCS(String name) {
    return jniJNI.SpatialReference_SetProjCS__SWIG_0(swigCPtr, this, name);
  }

  public int SetProjCS() {
    return jniJNI.SpatialReference_SetProjCS__SWIG_1(swigCPtr, this);
  }

  public int ImportFromWkt(String ppszInput) {
    return jniJNI.SpatialReference_ImportFromWkt(swigCPtr, this, ppszInput);
  }

  public int ImportFromProj4(String ppszInput) {
    return jniJNI.SpatialReference_ImportFromProj4(swigCPtr, this, ppszInput);
  }

  public int ImportFromUrl(String url) {
    return jniJNI.SpatialReference_ImportFromUrl(swigCPtr, this, url);
  }

  public int ImportFromESRI(java.util.Vector ppszInput) {
    return jniJNI.SpatialReference_ImportFromESRI(swigCPtr, this, ppszInput);
  }

  public int ImportFromEPSG(int arg) {
    return jniJNI.SpatialReference_ImportFromEPSG(swigCPtr, this, arg);
  }

  public int ImportFromEPSGA(int arg) {
    return jniJNI.SpatialReference_ImportFromEPSGA(swigCPtr, this, arg);
  }

  public int ImportFromPCI(String proj, String units, double[] argin) {
    return jniJNI.SpatialReference_ImportFromPCI__SWIG_0(swigCPtr, this, proj, units, argin);
  }

  public int ImportFromPCI(String proj, String units) {
    return jniJNI.SpatialReference_ImportFromPCI__SWIG_1(swigCPtr, this, proj, units);
  }

  public int ImportFromPCI(String proj) {
    return jniJNI.SpatialReference_ImportFromPCI__SWIG_2(swigCPtr, this, proj);
  }

  public int ImportFromUSGS(int proj_code, int zone, double[] argin, int datum_code) {
    return jniJNI.SpatialReference_ImportFromUSGS__SWIG_0(swigCPtr, this, proj_code, zone, argin, datum_code);
  }

  public int ImportFromUSGS(int proj_code, int zone, double[] argin) {
    return jniJNI.SpatialReference_ImportFromUSGS__SWIG_1(swigCPtr, this, proj_code, zone, argin);
  }

  public int ImportFromUSGS(int proj_code, int zone) {
    return jniJNI.SpatialReference_ImportFromUSGS__SWIG_2(swigCPtr, this, proj_code, zone);
  }

  public int ImportFromUSGS(int proj_code) {
    return jniJNI.SpatialReference_ImportFromUSGS__SWIG_3(swigCPtr, this, proj_code);
  }

  public int ImportFromXML(String xmlString) {
    return jniJNI.SpatialReference_ImportFromXML(swigCPtr, this, xmlString);
  }

  public int ImportFromERM(String proj, String datum, String units) {
    return jniJNI.SpatialReference_ImportFromERM(swigCPtr, this, proj, datum, units);
  }

  public int ImportFromMICoordSys(String pszCoordSys) {
    return jniJNI.SpatialReference_ImportFromMICoordSys(swigCPtr, this, pszCoordSys);
  }

  public int ExportToWkt(String[] argout) {
    return jniJNI.SpatialReference_ExportToWkt(swigCPtr, this, argout);
  }

  public int ExportToPrettyWkt(String[] argout, int simplify) {
    return jniJNI.SpatialReference_ExportToPrettyWkt__SWIG_0(swigCPtr, this, argout, simplify);
  }

  public int ExportToPrettyWkt(String[] argout) {
    return jniJNI.SpatialReference_ExportToPrettyWkt__SWIG_1(swigCPtr, this, argout);
  }

  public int ExportToProj4(String[] argout) {
    return jniJNI.SpatialReference_ExportToProj4(swigCPtr, this, argout);
  }

  public int ExportToPCI(String[] proj, String[] units, double[] parms) {
    return jniJNI.SpatialReference_ExportToPCI(swigCPtr, this, proj, units, parms);
  }

  public int ExportToUSGS(int[] code, int[] zone, double[] parms, int[] datum) {
    return jniJNI.SpatialReference_ExportToUSGS(swigCPtr, this, code, zone, parms, datum);
  }

  public int ExportToXML(String[] argout, String dialect) {
    return jniJNI.SpatialReference_ExportToXML__SWIG_0(swigCPtr, this, argout, dialect);
  }

  public int ExportToXML(String[] argout) {
    return jniJNI.SpatialReference_ExportToXML__SWIG_1(swigCPtr, this, argout);
  }

  public int ExportToMICoordSys(String[] argout) {
    return jniJNI.SpatialReference_ExportToMICoordSys(swigCPtr, this, argout);
  }

  public SpatialReference CloneGeogCS() {
    long cPtr = jniJNI.SpatialReference_CloneGeogCS(swigCPtr, this);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, true);
  }

  public SpatialReference Clone() {
    long cPtr = jniJNI.SpatialReference_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new SpatialReference(cPtr, true);
  }

  public int Validate() {
    return jniJNI.SpatialReference_Validate(swigCPtr, this);
  }

  public int StripCTParms() {
    return jniJNI.SpatialReference_StripCTParms(swigCPtr, this);
  }

  public int FixupOrdering() {
    return jniJNI.SpatialReference_FixupOrdering(swigCPtr, this);
  }

  public int Fixup() {
    return jniJNI.SpatialReference_Fixup(swigCPtr, this);
  }

  public int MorphToESRI() {
    return jniJNI.SpatialReference_MorphToESRI(swigCPtr, this);
  }

  public int MorphFromESRI() {
    return jniJNI.SpatialReference_MorphFromESRI(swigCPtr, this);
  }

}
